export const config = {
  AUTH_SECRET: process.env.NEXTAUTH_SECRET as string,
  DB_NAME: process.env.DB_NAME as string,
  DB_DOMAIN: process.env.DB_DOMAIN as string,
  DB_PORT: process.env.DB_PORT || 5432,
  DB_USER: process.env.DB_USER as string,
  DB_PASSWORD: process.env.DB_PASSWORD as string,
  MODE_ENV: process.env.MODE_ENV as string,
  JWT_SECRET: process.env.JWT_TOKEN_SECRET as string,
  LOGIN_ENDPOINT: process.env.NEXT_PUBLIC_LOGIN_ENDPOINT as string,
  VERIFY_CODE_ENDPOINT: process.env.NEXT_PUBLIC_VERIFY_PASSWORD_CODE_ENDPOINT as string,
  SEND_EMAIL_CODE_ENDPOINT: process.env.NEXT_PUBLIC_SEND_EMAIL_RECOVERY_ENDPOINT as string,
  USERS_ENDPOINT: process.env.NEXT_PUBLIC_USERS_ENDPOINT as string,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET as string,
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID as string,
  GOOGLE_CREATE_USER_ENDPOINT: process.env.NEXT_PUBLIC_GOOGLE_CREATE_USER_ENDPOINT as string,
  GEN_PROVIDER_TOKEN_ENDPOINT: process.env.NEXT_PUBLIC_GEN_PROVIDER_TOKEN_LOGIN_ENDPOINT as string,
  HOST_BASE: process.env.NEXT_PUBLIC_HOST_BASE as string,
};
